
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 18 14:54:22 GMT 2012
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMOP = 36;
  public static final int POW = 27;
  public static final int CHAR = 42;
  public static final int LPAREN = 12;
  public static final int SEMI = 14;
  public static final int REPEAT = 20;
  public static final int INT = 44;
  public static final int MINUS = 30;
  public static final int RPAREN = 13;
  public static final int NOT = 29;
  public static final int LCURL = 25;
  public static final int TYPE = 39;
  public static final int TDEF = 24;
  public static final int BOOL = 43;
  public static final int COMMA = 2;
  public static final int DIV = 31;
  public static final int UNTIL = 21;
  public static final int NUM = 40;
  public static final int PLUS = 41;
  public static final int BOOLOP = 35;
  public static final int ASSIGN = 11;
  public static final int IF = 16;
  public static final int DOT = 5;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int error = 1;
  public static final int PIPE = 9;
  public static final int SEQOP = 37;
  public static final int FDEF = 23;
  public static final int VOID = 28;
  public static final int LBRACK = 6;
  public static final int COMPOP = 38;
  public static final int RCURL = 26;
  public static final int TIMES = 8;
  public static final int COLON = 15;
  public static final int ELSE = 18;
  public static final int BEGINTUP = 3;
  public static final int EQQ = 10;
  public static final int RBRACK = 7;
  public static final int WHILE = 17;
  public static final int FLOAT = 45;
  public static final int ENDTUP = 4;
  public static final int STRING = 33;
  public static final int KEY = 34;
  public static final int DO = 19;
}

