
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 20 02:25:40 GMT 2012
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int POWER = 9;
  public static final int CHAR = 48;
  public static final int CONCAT = 16;
  public static final int STR = 32;
  public static final int LPAREN = 21;
  public static final int GREATER = 12;
  public static final int SEMI = 27;
  public static final int REPEAT = 38;
  public static final int INT = 46;
  public static final int RBRAC = 24;
  public static final int LESS = 10;
  public static final int MINUS = 7;
  public static final int RPAREN = 22;
  public static final int NOT = 2;
  public static final int LCURL = 19;
  public static final int AND = 4;
  public static final int TYPE = 30;
  public static final int LTUPLE = 33;
  public static final int TDEF = 42;
  public static final int IN = 17;
  public static final int OR = 3;
  public static final int BOOL = 45;
  public static final int COMMA = 28;
  public static final int UNTIL = 40;
  public static final int PLUS = 5;
  public static final int IF = 35;
  public static final int LESSEQ = 11;
  public static final int RTUPLE = 34;
  public static final int ID = 44;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int error = 1;
  public static final int FDEF = 43;
  public static final int VOID = 31;
  public static final int EQ = 25;
  public static final int RCURL = 20;
  public static final int TIMES = 6;
  public static final int COLON = 26;
  public static final int ELSE = 36;
  public static final int NOTIN = 18;
  public static final int EQQ = 14;
  public static final int WHILE = 37;
  public static final int FLOAT = 47;
  public static final int NOTEQQ = 15;
  public static final int GREATEREQ = 13;
  public static final int LBRAC = 23;
  public static final int DO = 39;
}

